### ISSUE TITLE
CircleCI Partner Review

### ISSUE THREAD

**Issue by EricRibeiro** [soos-io/soos-ci-analysis-circleci-orb#3]
Hello SOOS team 👋

I am from the @circleci Community and Partner Engineering team, here to help with a review for the CircleCI orb partnership. I have a few action items below for you:

**Changes:**

- Remove unnecessary parameters from the executor provided:

Unless I am missing something, the only parameter you require in your executor is the [tag](https://github.com/soos-io/soos-ci-analysis-circleci-orb/blob/main/orb.yml#L130). The rest are only used in your jobs/command.

- Fix tag parameter description:

Your [parameter description](https://github.com/soos-io/soos-ci-analysis-circleci-orb/blob/main/orb.yml#L133) mentions `node`. I believe this should be `python` based on the executor's name and docker image.

- Consider changing the `on_failure` parameter to enum or link to docs with the parameter's options:

It sounds like this parameter has multiple options, but I couldn't easily find the accepted arguments in the orb or your docs. It's a good idea to make it an [enum](https://circleci.com/docs/2.0/reusing-config/#enum) and/or insert the docs URL in the parameter description ([example](https://github.com/CircleCI-Public/slack-orb/blob/master/src/commands/notify.yml#L11)) for more information.

- Change the `mode` parameter to enum.

You did an excellent job explaining the valid arguments, and I believe you could further enforce them by making this parameter an [enum](https://circleci.com/docs/2.0/reusing-config/#enum).

- Remove empty spaces between jobs parameters and `requires`.

Remove the lines: [206](https://github.com/soos-io/soos-ci-analysis-circleci-orb/blob/main/orb.yml#L206) and [270](https://github.com/soos-io/soos-ci-analysis-circleci-orb/blob/main/orb.yml#L270).

- Remove the mode parameter options and their explanations from the soos-analysis [job description](https://github.com/soos-io/soos-ci-analysis-circleci-orb/blob/main/orb.yml#L281).

The options are listed and explained in the [parameter description](https://github.com/soos-io/soos-ci-analysis-circleci-orb/blob/main/orb.yml#L307). There is no need to duplicate this information in the job description.

**Optional:**

- Consider writing your orb using CircleCI's [Orb Development Kit](https://circleci.com/docs/2.0/orb-author/#orb-development-kit). It will increase your orb's maintainability and make it easier to extend its functionality in the future, should it be needed.

**Questions:**

- I can see some parameters in the command that are not explicitly used in your orb. Some examples are `SOOS_BUILD_URI` and `SOOS_OPERATING_ENVIRONMENT`. Do they serve any purpose?

After addressing the issues above, please provide us with a successful run link. Should you have any questions, feel free to post them here, and I'll be happy to help!

**Comment by SOOS-JAlvarez** [comment]
@EricRibeiro Hey Eric, thanks for the review, and sorry for the late response, I've just implemented the changes according to this review.
Regarding your questions it seems that the `SOOS_OPERATING_ENVIRONMENT` is not necessary anymore for us so I'll just deleted it, and the `SOOS_BUILD_URI` was missing on our python command so i've just added that.
Let me know if there's something else we should change.
Thanks in advance.

**Comment by EricRibeiro** [comment]
Thank you, @SOOS-JAlvarez!

> Remove unnecessary parameters from the executor provided

Can you double-check the item above? I still see several parameters in the executor that I am unsure of the purpose.

> Regarding your questions it seems that the SOOS_OPERATING_ENVIRONMENT is not necessary anymore for us so I'll just deleted it, and the SOOS_BUILD_URI was missing on our python command so i've just added that.

Thanks for clarifying. The following are also not explicitly used in the orb, can you check them too:

- SOOS_COMMIT_HASH
- SOOS_BRANCH_NAME
- SOOS_BRANCH_URI
- SOOS_BUILD_VERSION
- SOOS_INTEGRATION_NAME
- SOOS_CLIENT_ID
- SOOS_API_KEY

**Comment by SOOS-JAlvarez** [comment]
Hey @EricRibeiro , thanks for the quick response, I've just done the final cleanup according to your latest comment.
Regarding `Remove unnecessary parameters from the executor provided` you've mention, I cannot remove any parameter from there because the orb will throw an error as invalid for referencing undeclared arguments without declared parameters.
Thanks!

**Comment by EricRibeiro** [comment]
Would you mind sharing a link with the error? I might be able to help you.

**Comment by SOOS-JAlvarez** [comment]
> Would you mind sharing a link with the error? I might be able to help you.

I've just created https://github.com/soos-io/soos-ci-analysis-circleci-orb/pull/6 with an example where I've removed a parameter from tag and the error it throws when running  `circleci orb validate orb.yml`

**Comment by EricRibeiro** [comment]
Thank you!

That's happening because even though you removed the parameter from the executor definition, you still pass it as an argument when using the executor. Take a look at:

https://github.com/soos-io/soos-ci-analysis-circleci-orb/blob/76a08dc771296e6a419c4760b92b31da4ee20d44/orb.yml#L376
https://github.com/soos-io/soos-ci-analysis-circleci-orb/blob/76a08dc771296e6a419c4760b92b31da4ee20d44/orb.yml#L452
https://github.com/soos-io/soos-ci-analysis-circleci-orb/blob/76a08dc771296e6a419c4760b92b31da4ee20d44/orb.yml#L527
https://github.com/soos-io/soos-ci-analysis-circleci-orb/blob/76a08dc771296e6a419c4760b92b31da4ee20d44/orb.yml#L602

You need to remove all of these as well. From my understanding of your orb, the only argument you truly require in your executor is the `tag`.

**Comment by SOOS-JAlvarez** [comment]
@EricRibeiro, I've just merged the changes as suggested on https://github.com/soos-io/soos-ci-analysis-circleci-orb/pull/6, here's a link to a successfull run of that orb https://app.circleci.com/pipelines/github/SOOS-JAlvarez/circleci-test-public/30/workflows/74062d9f-511f-4de8-b6f5-68022b270138/jobs/40

**Comment by EricRibeiro** [comment]
Awesome! Thanks, @SOOS-JAlvarez 🙇 

If you take a look at the SCA [orb registry page](https://circleci.com/developer/orbs/orb/soos-io/sca), most parameters from the `analysis_run_and_wait`, `analysis_async_init` and `analysis_async_result` lack descriptions. Would you mind including it? It seems like these jobs share parameters with `soos-analysis`, so you can copy and paste the descriptions.

After that is done, I'll need your company logo to certify the orb. Feel free to send it to me at `eric.ribeiro@circleci.com` or via Emily Peden.

On another note, I haven't heard back from your team on the DAST orb. Let me know when it is ready, so I can review it 😄

**Comment by SOOS-JAlvarez** [comment]
Thanks again! I've just added those missing descriptions, I'm going to talk with Emily so she sends you the company logo and to get an update on the DAST Orb which I haven't been involved so far.
